services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=kansweb
    depends_on:
      - db
  
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=kansweb
    ports:
      - "5433:5432"
    volumes:
      - ./db/kansweb.sql:/docker-entrypoint-initdb.d/kansweb.sql
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh